name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set error flag to false
        run: echo "ERROR_STEP=false" >> $GITHUB_ENV

      # Other steps...

      - name: Create ECS task definition file
        run: |
          cat > ecs-task-def.json <<EOF
          {
            "family": "my-task-family",
            "executionRoleArn": "arn:aws:iam::637423558639:role/ecsTaskExecutionRole",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "hello-world-container",
                "image": "637423558639.dkr.ecr.ap-south-1.amazonaws.com/hello-world:latest",
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ]
              }
            ],
            "requiresCompatibilities": [
              "FARGATE"
            ],
            "cpu": "256",
            "memory": "512"
          }
          EOF
        working-directory: ${{ github.workspace }}
        if: env.ERROR_STEP != 'true'

      # Other steps...

      - name: Check if ECS task definition file exists
        id: check-task-def-exists
        run: |
          if [ -f "ecs-task-def.json" ]; then
            echo "::set-output name=file-exists::true"
          else
            echo "::set-output name=file-exists::false"
          fi
        continue-on-error: true
        if: env.ERROR_STEP != 'true'

      - name: Register ECS Task Definition
        id: register-task-def
        run: |
          if [ "${{ steps.check-task-def-exists.outputs.file-exists }}" == "true" ]; then
            TASK_DEFINITION=$(cat ecs-task-def.json)
            echo "$TASK_DEFINITION" | jq .
            REGISTERED_TASK_DEFINITION=$(aws ecs register-task-definition --cli-input-json "$TASK_DEFINITION")
            TASK_DEFINITION_ARN=$(echo $REGISTERED_TASK_DEFINITION | jq -r '.taskDefinition.taskDefinitionArn')
            echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> $GITHUB_ENV
          else
            echo "ECS task definition file not found. Skipping registration."
            echo "ERROR_STEP=true" >> $GITHUB_ENV
          fi
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: env.ERROR_STEP != 'true'

      # Other steps...

      - name: Deploy to ECS
        if: success() && env.TASK_DEFINITION_ARN != '' && env.ERROR_STEP != 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ env.TASK_DEFINITION_ARN }}
          service: hello-world-service
          cluster: hello-world-cluster
          wait-for-service-stability: true
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
